/* ==========================================================================
   YIYI ESSENCE · CATÁLOGO
   --------------------------------------------------------------------------
   IMPORTANTE: los productos, marcas y precios de este archivo son EJEMPLOS
   para que veas cómo funciona la tienda. Reemplázalos por tus productos reales.

   Cómo agregar un producto: copia un bloque { ... }, cambia los datos y
   asegúrate de que el "id" sea único (sin espacios ni tildes).

   Campos:
     id          Identificador único (se usa en la URL del producto)
     name        Nombre visible
     brand       Marca
     category    Debe coincidir con el "id" de una categoría de abajo
     subcategory Texto libre (opcional)
     price       Precio actual en soles
     oldPrice    Precio anterior (opcional). Si es mayor que "price", se muestra
                 el descuento y el producto aparece en "Ofertas".
     stock       Unidades disponibles. 0 = "Agotado" (no se puede agregar)
     featured    true = aparece en "Destacados"
     added       Fecha de ingreso (AAAA-MM-DD). Sirve para "Novedades"
     size        Contenido (ej. "30 ml")
     description Descripción breve (evita promesas médicas o resultados garantizados)
     image       Ruta de la imagen (carpeta assets/images/products/)
   ========================================================================== */

/* Categorías: puedes agregar más líneas. "ofertas" es especial: muestra
   automáticamente los productos que tienen oldPrice mayor que price. */
window.YIYI_CATEGORIES = [
  { id: "maquillaje", name: "Maquillaje", icon: "lips", blurb: "Labios, rostro, ojos y uñas." },
  { id: "skincare", name: "Skincare", icon: "drop", blurb: "Sérums, hidratantes y protección diaria." },
  { id: "cuidado-facial", name: "Cuidado facial", icon: "leaf", blurb: "Limpieza, tónicos y mascarillas." },
  { id: "cuidado-corporal", name: "Cuidado corporal", icon: "petal", blurb: "Cremas, exfoliantes y brumas." },
  { id: "cabello", name: "Cabello", icon: "wave", blurb: "Shampoo, mascarillas y aceites." },
  { id: "fragancias", name: "Perfumes y fragancias", icon: "flask", blurb: "Aromas florales, cálidos y frescos." },
  { id: "accesorios", name: "Accesorios", icon: "brush", blurb: "Brochas, esponjas y herramientas." },
  { id: "sets", name: "Sets y kits", icon: "gift", blurb: "Rutinas completas y regalos." },
  { id: "ofertas", name: "Ofertas", icon: "tag", blurb: "Precios especiales por tiempo limitado.", virtual: true },
];

window.YIYI_PRODUCTS = [
  /* ---------------- Maquillaje ---------------- */
  {
    id: "labial-satinado-rosa-nude",
    name: "Labial Satinado Rosa Nude",
    brand: "Velvet Muse",
    category: "maquillaje",
    subcategory: "Labios",
    price: 24.9,
    stock: 18,
    featured: true,
    added: "2026-08-20",
    size: "3.5 g",
    description: "Labial de acabado satinado en un tono rosa nude versátil para el día a día.",
    image: "assets/images/products/labial-satinado-rosa-nude.svg",
  },
  {
    id: "labial-mate-malva",
    name: "Labial Mate Malva",
    brand: "Velvet Muse",
    category: "maquillaje",
    subcategory: "Labios",
    price: 26.9,
    oldPrice: 32.9,
    stock: 12,
    added: "2026-07-15",
    size: "3.5 g",
    description: "Color malva de acabado mate y textura cómoda. Ideal para looks de noche.",
    image: "assets/images/products/labial-mate-malva.svg",
  },
  {
    id: "base-fluida-luminosa",
    name: "Base Fluida Acabado Luminoso",
    brand: "Nácar",
    category: "maquillaje",
    subcategory: "Rostro",
    price: 49.9,
    stock: 9,
    added: "2026-06-30",
    size: "30 ml",
    description: "Base de cobertura media con acabado luminoso. Disponible en varios tonos (consulta por WhatsApp).",
    image: "assets/images/products/base-fluida-luminosa.svg",
  },
  {
    id: "rubor-crema-petalo",
    name: "Rubor en Crema Pétalo",
    brand: "Rosé Atelier",
    category: "maquillaje",
    subcategory: "Rostro",
    price: 28.9,
    stock: 20,
    featured: true,
    added: "2026-09-28",
    size: "6 g",
    description: "Rubor cremoso de rosa suave, fácil de difuminar con los dedos o con brocha.",
    image: "assets/images/products/rubor-crema-petalo.svg",
  },
  {
    id: "paleta-sombras-champagne",
    name: "Paleta de Sombras Champagne · 9 tonos",
    brand: "Rosé Atelier",
    category: "maquillaje",
    subcategory: "Ojos",
    price: 59.9,
    oldPrice: 74.9,
    stock: 7,
    featured: true,
    added: "2026-08-05",
    size: "9 x 1.2 g",
    description: "Nueve tonos entre nude, champagne y malva, con acabados mate y satinados.",
    image: "assets/images/products/paleta-sombras-champagne.svg",
  },
  {
    id: "mascara-pestanas-volumen",
    name: "Máscara de Pestañas Volumen",
    brand: "Velvet Muse",
    category: "maquillaje",
    subcategory: "Ojos",
    price: 32.9,
    stock: 25,
    added: "2026-05-18",
    size: "9 ml",
    description: "Máscara de color negro con cepillo flexible para separar y definir las pestañas.",
    image: "assets/images/products/mascara-pestanas-volumen.svg",
  },
  {
    id: "polvo-compacto-traslucido",
    name: "Polvo Compacto Traslúcido",
    brand: "Nácar",
    category: "maquillaje",
    subcategory: "Rostro",
    price: 29.9,
    stock: 14,
    added: "2026-04-22",
    size: "8 g",
    description: "Polvo compacto de acabado suave para fijar el maquillaje sin marcar textura.",
    image: "assets/images/products/polvo-compacto-traslucido.svg",
  },
  {
    id: "esmalte-rosa-empolvado",
    name: "Esmalte Rosa Empolvado",
    brand: "Rosé Atelier",
    category: "maquillaje",
    subcategory: "Uñas",
    price: 14.9,
    stock: 30,
    added: "2026-09-25",
    size: "10 ml",
    description: "Esmalte de uñas en tono rosa empolvado con acabado cremoso.",
    image: "assets/images/products/esmalte-rosa-empolvado.svg",
  },

  /* ---------------- Skincare ---------------- */
  {
    id: "serum-vitamina-c",
    name: "Sérum Vitamina C",
    brand: "Aura Lab",
    category: "skincare",
    subcategory: "Sérums",
    price: 69.9,
    oldPrice: 84.9,
    stock: 11,
    featured: true,
    added: "2026-09-10",
    size: "30 ml",
    description: "Sérum de textura ligera para incorporar en tu rutina de cuidado facial diaria.",
    image: "assets/images/products/serum-vitamina-c.svg",
  },
  {
    id: "serum-acido-hialuronico",
    name: "Sérum Hidratante con Ácido Hialurónico",
    brand: "Aura Lab",
    category: "skincare",
    subcategory: "Sérums",
    price: 64.9,
    stock: 8,
    added: "2026-07-30",
    size: "30 ml",
    description: "Sérum de base acuosa para una sensación de piel hidratada y confortable.",
    image: "assets/images/products/serum-acido-hialuronico.svg",
  },
  {
    id: "crema-hidratante-facial",
    name: "Crema Hidratante Facial",
    brand: "Lumi Botánica",
    category: "skincare",
    subcategory: "Hidratantes",
    price: 54.9,
    stock: 16,
    added: "2026-06-12",
    size: "50 ml",
    description: "Crema de textura sedosa para el uso diario, de rápida absorción.",
    image: "assets/images/products/crema-hidratante-facial.svg",
  },
  {
    id: "protector-solar-fps50",
    name: "Protector Solar Facial FPS 50",
    brand: "Lumi Botánica",
    category: "skincare",
    subcategory: "Protección solar",
    price: 44.9,
    stock: 22,
    featured: true,
    added: "2026-09-02",
    size: "50 ml",
    description: "Protector solar facial de toque seco. Reaplicar según las indicaciones del envase.",
    image: "assets/images/products/protector-solar-fps50.svg",
  },
  {
    id: "contorno-ojos",
    name: "Contorno de Ojos",
    brand: "Aura Lab",
    category: "skincare",
    subcategory: "Contorno de ojos",
    price: 47.9,
    stock: 10,
    added: "2026-09-27",
    size: "15 ml",
    description: "Crema ligera para el área del contorno de ojos, con aplicador de punta suave.",
    image: "assets/images/products/contorno-ojos.svg",
  },

  /* ---------------- Cuidado facial ---------------- */
  {
    id: "gel-limpiador-suave",
    name: "Gel Limpiador Facial Suave",
    brand: "Lumi Botánica",
    category: "cuidado-facial",
    subcategory: "Limpieza",
    price: 29.9,
    stock: 28,
    added: "2026-05-02",
    size: "150 ml",
    description: "Gel limpiador de espuma ligera para el rostro, apto para el uso diario.",
    image: "assets/images/products/gel-limpiador-suave.svg",
  },
  {
    id: "agua-micelar",
    name: "Agua Micelar Desmaquillante",
    brand: "Casa Petal",
    category: "cuidado-facial",
    subcategory: "Limpieza",
    price: 24.9,
    oldPrice: 29.9,
    stock: 35,
    added: "2026-04-10",
    size: "200 ml",
    description: "Agua micelar para retirar maquillaje y limpiar el rostro en un solo paso.",
    image: "assets/images/products/agua-micelar.svg",
  },
  {
    id: "mascarilla-arcilla-rosa",
    name: "Mascarilla de Arcilla Rosa",
    brand: "Casa Petal",
    category: "cuidado-facial",
    subcategory: "Mascarillas",
    price: 34.9,
    stock: 13,
    added: "2026-08-12",
    size: "100 ml",
    description: "Mascarilla de arcilla rosa para usar de forma semanal como parte de tu rutina.",
    image: "assets/images/products/mascarilla-arcilla-rosa.svg",
  },
  {
    id: "tonico-facial-suave",
    name: "Tónico Facial sin Alcohol",
    brand: "Casa Petal",
    category: "cuidado-facial",
    subcategory: "Tónicos",
    price: 31.9,
    stock: 0,
    added: "2026-07-01",
    size: "150 ml",
    description: "Tónico facial de textura acuosa, formulado sin alcohol.",
    image: "assets/images/products/tonico-facial-suave.svg",
  },

  /* ---------------- Cuidado corporal ---------------- */
  {
    id: "crema-corporal-vainilla",
    name: "Crema Corporal Vainilla y Almendra",
    brand: "Casa Petal",
    category: "cuidado-corporal",
    subcategory: "Cremas",
    price: 27.9,
    stock: 24,
    added: "2026-06-05",
    size: "250 ml",
    description: "Crema corporal de aroma suave a vainilla y almendra, de rápida absorción.",
    image: "assets/images/products/crema-corporal-vainilla.svg",
  },
  {
    id: "exfoliante-corporal-azucar",
    name: "Exfoliante Corporal de Azúcar",
    brand: "Lumi Botánica",
    category: "cuidado-corporal",
    subcategory: "Exfoliantes",
    price: 32.9,
    stock: 15,
    added: "2026-09-29",
    size: "200 g",
    description: "Exfoliante con granos de azúcar para usar en la ducha, con aroma dulce y delicado.",
    image: "assets/images/products/exfoliante-corporal-azucar.svg",
  },
  {
    id: "bruma-corporal-peonia",
    name: "Bruma Corporal Peonía",
    brand: "Rosé Atelier",
    category: "cuidado-corporal",
    subcategory: "Brumas",
    price: 29.9,
    oldPrice: 36.9,
    stock: 17,
    added: "2026-05-28",
    size: "120 ml",
    description: "Bruma perfumada de notas florales para refrescar tu día.",
    image: "assets/images/products/bruma-corporal-peonia.svg",
  },

  /* ---------------- Cabello ---------------- */
  {
    id: "shampoo-hidratante",
    name: "Shampoo Hidratante",
    brand: "Lumi Botánica",
    category: "cabello",
    subcategory: "Shampoo",
    price: 28.9,
    stock: 26,
    added: "2026-05-14",
    size: "300 ml",
    description: "Shampoo de limpieza suave para el uso frecuente en todo tipo de cabello.",
    image: "assets/images/products/shampoo-hidratante.svg",
  },
  {
    id: "mascarilla-capilar-nutritiva",
    name: "Mascarilla Capilar Nutritiva",
    brand: "Lumi Botánica",
    category: "cabello",
    subcategory: "Tratamientos",
    price: 38.9,
    stock: 12,
    featured: true,
    added: "2026-08-18",
    size: "250 ml",
    description: "Mascarilla cremosa para aplicar después del shampoo y dejar el cabello suave.",
    image: "assets/images/products/mascarilla-capilar-nutritiva.svg",
  },
  {
    id: "aceite-capilar-ligero",
    name: "Aceite Capilar Ligero",
    brand: "Aura Lab",
    category: "cabello",
    subcategory: "Aceites",
    price: 36.9,
    stock: 9,
    added: "2026-07-22",
    size: "60 ml",
    description: "Aceite de textura ligera para las puntas, con acabado brillante y sin sensación pesada.",
    image: "assets/images/products/aceite-capilar-ligero.svg",
  },

  /* ---------------- Fragancias ---------------- */
  {
    id: "perfume-peonia-ambar",
    name: "Eau de Parfum Peonía y Ámbar",
    brand: "Nácar",
    category: "fragancias",
    subcategory: "Para ella",
    price: 129.9,
    oldPrice: 149.9,
    stock: 6,
    featured: true,
    added: "2026-08-30",
    size: "50 ml",
    description: "Fragancia floral cálida con notas de peonía y ámbar. Perfecta para ocasiones especiales.",
    image: "assets/images/products/perfume-peonia-ambar.svg",
  },
  {
    id: "perfume-vainilla-blanca",
    name: "Eau de Parfum Vainilla Blanca",
    brand: "Nácar",
    category: "fragancias",
    subcategory: "Para ella",
    price: 119.9,
    stock: 8,
    added: "2026-09-26",
    size: "50 ml",
    description: "Aroma dulce y envolvente de vainilla con un fondo suave de maderas claras.",
    image: "assets/images/products/perfume-vainilla-blanca.svg",
  },

  /* ---------------- Accesorios ---------------- */
  {
    id: "brocha-base-difuminadora",
    name: "Brocha para Base Difuminadora",
    brand: "Rosé Atelier",
    category: "accesorios",
    subcategory: "Brochas",
    price: 19.9,
    stock: 40,
    added: "2026-05-09",
    size: "1 unidad",
    description: "Brocha de cerdas sintéticas suaves para aplicar base líquida o en crema.",
    image: "assets/images/products/brocha-base-difuminadora.svg",
  },
  {
    id: "esponjas-maquillaje-duo",
    name: "Esponjas de Maquillaje · Dúo",
    brand: "Rosé Atelier",
    category: "accesorios",
    subcategory: "Esponjas",
    price: 17.9,
    stock: 33,
    added: "2026-06-20",
    size: "2 unidades",
    description: "Dos esponjas de maquillaje en forma de gota para difuminar con suavidad.",
    image: "assets/images/products/esponjas-maquillaje-duo.svg",
  },

  /* ---------------- Sets y kits ---------------- */
  {
    id: "set-rutina-facial",
    name: "Set Rutina Facial · Limpiar, tonificar e hidratar",
    brand: "Lumi Botánica",
    category: "sets",
    subcategory: "Rutinas",
    price: 99.9,
    oldPrice: 119.9,
    stock: 5,
    featured: true,
    added: "2026-09-15",
    size: "3 productos",
    description: "Set de tres pasos para empezar una rutina facial sencilla: limpiador, tónico y crema.",
    image: "assets/images/products/set-rutina-facial.svg",
  },
  {
    id: "set-brochas-rose",
    name: "Set de 5 Brochas Rosé",
    brand: "Rosé Atelier",
    category: "sets",
    subcategory: "Brochas",
    price: 64.9,
    stock: 10,
    added: "2026-07-08",
    size: "5 piezas",
    description: "Cinco brochas de maquillaje para rostro y ojos, con estuche de presentación.",
    image: "assets/images/products/set-brochas-rose.svg",
  },
  {
    id: "kit-regalo-fragancia",
    name: "Kit Regalo Fragancia y Crema",
    brand: "Nácar",
    category: "sets",
    subcategory: "Regalos",
    price: 149.9,
    stock: 4,
    added: "2026-09-30",
    size: "2 productos",
    description: "Kit de regalo con Eau de Parfum de 50 ml y crema corporal, en caja de presentación.",
    image: "assets/images/products/kit-regalo-fragancia.svg",
  },
];
